version: '3.8'
services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "9000:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped

  taskly:
    build: .
    image: taskly
    container_name: taskly
    ports:
      - "9001:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres-db


