spring:
  application:
    name: taskly
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres-db:5432/postgres
  liquibase:
    enabled: true
    change-log: classpath*:db/changelog-master.yml
    drop-first: true
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: none

server:
  port: 8080